### ISSUE TITLE
Cannot edit/deactivate/activate/delete a form or the form field

### ISSUE THREAD

**Issue by srutto** [ushahidi/uchaguzi#32]
Go to Manage/Forms
Add a form "Test" and save
Click on "Edit" or "Delete" or "Active" or "Edit form field"

Nothing happens, missing functionality

**Comment by rjmackay** [comment]
This might be fixed by e474b64 (pushed today) .. can you check if you had
that commit or not?

On Thu, Jan 24, 2013 at 12:15 PM, Sharon Rutto notifications@github.comwrote:

> Go to Manage/Forms
> Add a form "Test" and save
> Click on "Edit" or "Delete" or "Active" or "Edit form field"
> 
> Nothing happens, missing functionality
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ushahidi/uchaguzi/issues/32.

## 

Robbie Mackay

Software Developer, External Projects
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay

**Comment by srutto** [comment]
Oh yes, I didn't have it, just pulled it in. Seems fine now. Although when you click on "Active", after confirming "Show/Hide", the status still remains "Active". It doesn't change to hidden if it is, so you can't know whether it's hidden or it's active. You just get the notification saying the form has been modified. See -> 
![Screen Shot 2013-01-24 at 2 56 05 PM](https://f.cloud.github.com/assets/1751822/93360/3fdf41b4-661e-11e2-8159-a643ecf4c9a6.png)

**Comment by kamaulynder** [comment]
Closing this as functionality is fine.
