### ISSUE TITLE
Calibration missing in the get radius section in "Get Alerts" page

### ISSUE THREAD

**Issue by srutto** [ushahidi/uchaguzi#34]
![Screen Shot 2013-01-24 at 2 41 08 PM](https://f.cloud.github.com/assets/1751822/93365/e8901b80-661e-11e2-93f2-15ce8a5b3f97.png)
Go to "Get Alerts" page
Go to "Select your city or location"
![Screen Shot 2013-01-24 at 2 40 03 PM](https://f.cloud.github.com/assets/1751822/93364/cdac179c-661e-11e2-848e-862eac6ba7e0.png)

**Comment by jetherton** [comment]
When I change my radius to 100 km the text at the top of the map, "Or place a spot on the map below, and we will alert you when a report is submitted within 20 kilometers." didn't update to say 100 kilometers instead of 20. I'm running chromium on ubuntu 12.04

Also, this is minor, but the color of the map and the background color of the site are very similar and kind of blend together. I realize this is a personal preference, but if it were up to me I'd add a border around the map.

**Comment by rjmackay** [comment]
I don't think the "Or place a spot on the map below, and we will alert you when a report is submitted within 20 kilometers." has ever been something that changed. However theres supposed to be a popup on the slider to indicate the current distance measure. This is current disappearing under the map
![Screen Shot 2013-02-20 at 4 09 50 PM](https://f.cloud.github.com/assets/7965/174374/061f7276-7b0b-11e2-9b3e-7b57e5ad0ce1.png)
