### ISSUE TITLE
Alerts Subscription Giving an error

### ISSUE THREAD

**Issue by Githinjimuchiri** [ushahidi/uchaguzi#81]
Subscribing for alerts gives this error:
Fatal error: Using $this when not in object context in /var/www/uchaguzi.co.ke/application/helpers/alert.php on line 34

**Comment by rjmackay** [comment]
This is fixed in core ushahidi on commit
https://github.com/ushahidi/Ushahidi_Web/commit/49a476226f95dd2ade9af684934b5e6d0a89cd46
needs to be ported

On Sun, Feb 24, 2013 at 12:15 AM, Githinjimuchiri
notifications@github.comwrote:

> Subscribing for alerts gives this error:
> Fatal error: Using $this when not in object context in /var/www/
> uchaguzi.co.ke/application/helpers/alert.php on line 34
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ushahidi/uchaguzi/issues/81.

## 

Robbie Mackay

Software Developer, External Projects
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay
