### ISSUE TITLE
Reports page, tools missing odd login behaviour

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#84]
1. click on home in ff (sorry in uchaguzi.co.ke)
2. click on tools
3. click on reports

(I did this twice to prove it. clicked around on a bunch of the buttons.)

The Tools link disappears in the dashboard (hard for navigation)  and the login button in the righthand side shows me logged in as someone else
![5x](https://f.cloud.github.com/assets/1216707/187984/e4e92c2a-7db0-11e2-9ee6-819bd4826067.png)

This is a p1 because security issue

**Comment by rjmackay** [comment]
This could be a caching issue - page cache is enabled and set to 1 minute on live. Though not one I've ever seen before.

**Comment by rjmackay** [comment]
I've disabled caching on live - that seems to have resolved the issue for now. I'm not quite sure if this is a bug in core too, but it could be due to the admin/frontend crossover in uchaguzi.
Please let me know if you're able to produce this error again.

ping @srutto this could do with a thorough test. Best done with multiple users logged in at once to see if you get any crossover. The basic issue is the server possibly caching someone elses logged in page and then serving it to another user.

**Comment by rrbaker** [comment]
Already spoke to Robbie about this on Skype but I could not reproduce this on my end with caching disabled.

**Comment by rjmackay** [comment]
Closing this for now
